openapi: 3.0.3
info:
  title: Staffing Management API
  version: 1.0.0
  description: API for managing staff records and information
servers:
  - url: https://api.staffing.com/v1
    description: Production server
  - url: https://staging-api.staffing.com/v1
    description: Staging server

paths:
  /staff:
    post:
      summary: Create a new staff member
      description: Creates a new staff member record in the system
      operationId: createStaff
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StaffCreate'
      responses:
        '201':
          description: Staff member created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Staff'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: List all staff members
      description: Retrieves a list of all staff members
      operationId: listStaff
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: List of staff members
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Staff'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /staff/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Unique identifier of the staff member
    get:
      summary: Get staff member by ID
      description: Retrieves a specific staff member by their ID
      operationId: getStaffById
      responses:
        '200':
          description: Staff member details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Staff'
        '404':
          description: Staff member not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update staff member
      description: Updates an existing staff member's information
      operationId: updateStaff
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StaffUpdate'
      responses:
        '200':
          description: Staff member updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Staff'
        '404':
          description: Staff member not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete staff member
      description: Removes a staff member from the system
      operationId: deleteStaff
      responses:
        '204':
          description: Staff member deleted successfully
        '404':
          description: Staff member not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Staff:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the staff member
        firstName:
          type: string
          description: First name of the staff member
        lastName:
          type: string
          description: Last name of the staff member
        email:
          type: string
          format: email
          description: Email address of the staff member
        position:
          type: string
          description: Job position of the staff member
        department:
          type: string
          description: Department the staff member belongs to
        hireDate:
          type: string
          format: date
          description: Date when the staff member was hired
        status:
          type: string
          enum: [active, inactive, on_leave]
          description: Current status of the staff member
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the record was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the record was last updated
      required:
        - id
        - firstName
        - lastName
        - email
        - position
        - status

    StaffCreate:
      type: object
      properties:
        firstName:
          type: string
          description: First name of the staff member
        lastName:
          type: string
          description: Last name of the staff member
        email:
          type: string
          format: email
          description: Email address of the staff member
        position:
          type: string
          description: Job position of the staff member
        department:
          type: string
          description: Department the staff member belongs to
      required:
        - firstName
        - lastName
        - email
        - position

    StaffUpdate:
      type: object
      properties:
        firstName:
          type: string
          description: First name of the staff member
        lastName:
          type: string
          description: Last name of the staff member
        email:
          type: string
          format: email
          description: Email address of the staff member
        position:
          type: string
          description: Job position of the staff member
        department:
          type: string
          description: Department the staff member belongs to
        status:
          type: string
          enum: [active, inactive, on_leave]
          description: Current status of the staff member

    Pagination:
      type: object
      properties:
        total:
          type: integer
          description: Total number of items
        page:
          type: integer
          description: Current page number
        limit:
          type: integer
          description: Number of items per page
        totalPages:
          type: integer
          description: Total number of pages

    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
        details:
          type: object
          description: Additional error details 